name: Workflow to check if environment can be extracted dynamically

on:
  push:
  #pull_request:
    #types: [opened, edited, reopened, synchronize]
    branches: [qa, staging]

jobs:
  determine-env:
    name: get the name of env
    outputs:
      saved-env: ${{ steps.step1.outputs.saved-env }}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        #run: echo "::set-output name=saved-env::staging"
        #run: |
#          if [[ "${{ github.event.ref }}" == "refs/heads/qa" ]]; then
#            echo "::set-output name=saved-env::qa"
#          fi
#          if [[ "${{ github.event.ref }}" == "refs/heads/staging" ]]; then
#            echo "::set-output name=saved-env::staging"
#          fi
        run: echo "::set-output name=saved-env::""${{ github.event.ref }}"

  check-environment-qa:
    name: Get envrionment name from branch name qa
    runs-on: ubuntu-latest
    needs: determine-env
    environment: QA
    #if: github.event.pull_request.base.ref == 'qa'
    #if: ${{ github.event.ref == 'refs/heads/qa' }}
    if: needs.determine-env.outputs.saved-env == 'refs/heads/qa'
    steps:
      - run: echo "Running on pr to QA"

  check-environment-staging:
    name: Get envrionment name from branch name staging
    runs-on: ubuntu-latest
    needs: determine-env
    environment: Staging
    #if: ${{ github.event.base_ref == 'refs/heads/staging' }}
    #if: ${{ github.event.ref == 'refs/heads/staging' }}
    if: ${{needs.determine-env.outputs.saved-env == 'refs/heads/staging'}}
    steps:
      - run: echo "Running on pr to Staging"