name: Workflow to check if environment can be extracted dynamically

on:
  #push:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [qa, staging]
jobs:
  check-environment-qa:
    name: Get envrionment name from branch name qa
    environment: QA
    if: github.event.pull_request.base.ref == 'refs/heads/qa'
    #if: ${{ github.event.ref == 'refs/heads/qa' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on pr to QA"
  check-environment-staging:
    name: Get envrionment name from branch name staging
    environment: Staging
    if: ${{ github.event.base_ref == 'refs/heads/staging' }}
    #if: ${{ github.event.ref == 'refs/heads/staging' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on pr to Staging"