name: Workflow to check if environment can be extracted dynamically

on:
  push:
  #pull_request:
    #types: [opened, edited, reopened, synchronize]
    branches: [qa, staging]

jobs:
  determine-env:
    name: get the name of env
    outputs:
      saved-env: ${{ steps.step1.outputs.saved-env }}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: echo "::set-output name=saved-env::qa"
        #run: if [ $github.event.ref == 'refs/heads/qa' ]; then github.event.ref; fi;

  check-environment-qa:
    name: Get envrionment name from branch name qa
    runs-on: ubuntu-latest
    needs: determine-env
    environment: QA
    #if: github.event.pull_request.base.ref == 'qa'
    #if: ${{ github.event.ref == 'refs/heads/qa' }}
    if: echo ${{needs.determine-env.outputs.saved-env}}
    steps:
      - run: echo "Running on pr to QA"
#  check-environment-staging:
#    name: Get envrionment name from branch name staging
#    environment: Staging
#    if: ${{ github.event.base_ref == 'refs/heads/staging' }}
#    #if: ${{ github.event.ref == 'refs/heads/staging' }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Running on pr to Staging"