# This workflow will validate and register a schema committed in code

name: Workflow to register schemas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout twist-kafka
      uses: actions/checkout@v2
      with:
        repository: pgupta-twistbioscience/twist-kafka 
    - name: Set up twist-kafka
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
