name: Workflow to test detection of checkins to a dir using actions

on:
  push

jobs:
  say-file-name-actions:
    name: Say Name of file checked in
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest commit from current branch
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter-files
        with:
          filters: |
            f1:
              - 'dir/**'
          list-files: 'shell'
      - name: trigger print
        if: steps.filter-files.outputs.f1 == 'true'
        run: echo "changed files" steps.filter-files.outputs.f1_count steps.filter-files.outputs.f1_files

