name: Workflow to test detection of checkins to a dir

on:
  push:
    paths:
      - 'dir/*'

jobs:
  say-file-name:
    name: Say Name of file checked in
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Echo running on push to $GITHUB_EVENT_PATH"

