name: Workflow to test detection of checkins to a dir

on:
  push:
    paths:
      - 'dir'

jobs:
  say-folder-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Echo running on push to dir'
